<?php
$f = "process.php";
$c = file_get_contents($f);
$c = str_replace("<?php include \"includes/header.php\"; ?>", "<?php include \"includes/header.php\"; \n\$sections = [];\nif (isset(\$conn)) {\n    \$r = \$conn->query(\"SELECT * FROM page_sections WHERE page = 'process'\");\n    while (\$row = \$r->fetch_assoc()) {\n        \$sections[\$row['section']] = \$row;\n    }\n}\n?>", $c);

// Replace hardcoded steps
$c = preg_replace("/<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-\[\#173F35\]\">Farm Sourcing<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-xs sm:text-sm leading-relaxed\">Rigorous farm selection across Egypt's key regions to ensure premium export quality\.<\/p>/", "<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step1']['heading'] ?? 'Farm Sourcing') ?></h2>\n        <p class=\"text-[#173F35]/70 text-xs sm:text-sm leading-relaxed\"><?= htmlspecialchars(\$sections['step1']['subtext'] ?? 'Rigorous farm selection across Egypts key regions to ensure premium export quality.') ?></p>", $c);

$c = preg_replace("/<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-\[\#173F35\]\">Harvesting<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-xs sm:text-sm leading-relaxed\">Carefully harvested precisely for optimal export windows, maintaining structural integrity\.<\/p>/", "<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step2']['heading'] ?? 'Harvesting') ?></h2>\n        <p class=\"text-[#173F35]/70 text-xs sm:text-sm leading-relaxed\"><?= htmlspecialchars(\$sections['step2']['subtext'] ?? 'Carefully harvested precisely for optimal export windows, maintaining structural integrity.') ?></p>", $c);

$c = preg_replace("/<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-\[\#173F35\]\">Quality Control<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-xs sm:text-sm leading-relaxed\">Stringent export-grade assessment for size, color, firmness, and natural perfection\.<\/p>/", "<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step3']['heading'] ?? 'Quality Control') ?></h2>\n        <p class=\"text-[#173F35]/70 text-xs sm:text-sm leading-relaxed\"><?= htmlspecialchars(\$sections['step3']['subtext'] ?? 'Stringent export-grade assessment for size, color, firmness, and natural perfection.') ?></p>", $c);

$c = preg_replace("/<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-\[\#173F35\]\">Packing<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-xs sm:text-sm leading-relaxed\">Packed in breathable, export-standard cartons designed to withstand long transit\.<\/p>/", "<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step4']['heading'] ?? 'Packing') ?></h2>\n        <p class=\"text-[#173F35]/70 text-xs sm:text-sm leading-relaxed\"><?= htmlspecialchars(\$sections['step4']['subtext'] ?? 'Packed in breathable, export-standard cartons designed to withstand long transit.') ?></p>", $c);

$c = preg_replace("/<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-\[\#173F35\]\">Cold Chain<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-xs sm:text-sm leading-relaxed\">Continuous refrigerated transport that strictly maintains optimal holding temperatures\.<\/p>/", "<h2 class=\"font-serif text-2xl sm:text-3xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step5']['heading'] ?? 'Cold Chain') ?></h2>\n        <p class=\"text-[#173F35]/70 text-xs sm:text-sm leading-relaxed\"><?= htmlspecialchars(\$sections['step5']['subtext'] ?? 'Continuous refrigerated transport that strictly maintains optimal holding temperatures.') ?></p>", $c);

$c = preg_replace("/<h2 class=\"font-serif text-3xl sm:text-4xl mb-2 text-\[\#173F35\]\">Global Shipment<\/h2>\s*<p class=\"text-\[\#173F35\]\/70 text-sm leading-relaxed mx-auto max-w-sm\">Complete customs clearance and seamless logistics management from port to port\.<\/p>/", "<h2 class=\"font-serif text-3xl sm:text-4xl mb-2 text-[#173F35]\"><?= htmlspecialchars(\$sections['step6']['heading'] ?? 'Global Shipment') ?></h2>\n        <p class=\"text-[#173F35]/70 text-sm leading-relaxed mx-auto max-w-sm\"><?= htmlspecialchars(\$sections['step6']['subtext'] ?? 'Complete customs clearance and seamless logistics management from port to port.') ?></p>", $c);

file_put_contents($f, $c);
echo "Updated process.php";
?>
